### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by EloCvll** [obcom/obcom.fr#21]

**Comment by EloCvll** [comment]
Mots clés à mettre en évidence sur le site obcom.fr / Revoir les paragraphes:

- Création de logiciels, comme par exemple avec l'idée du "sur-mesure" pour convenir à chacun. Répéter le mot "logiciel" ou utiliser synonyme tel que "application", "outil personnalisé".
- Utiliser le mot "solution" et pourquoi pas "accompagnement" en parlant du développement informatique des structures.
- Création, réalisation, conception,
- Synonyme à "informatique" : digital, numérique, interface, processus,
- Optimisation du temps de travail/du travail.


Dans le paragraphe d'introduction, peut-être énumérer les services dont dispose Obcom et ainsi mettre en évidence les mots-clés tels que "développement web", "création de logiciels". Parler de services "sur-mesure" pour améliorer/rendre efficient/faire gagner en visibilité les entreprises.

Étoffer le paragraphe "Formation" en expliquant les méthodes d'accompagnement, les types de logiciels utilisés. On peut aussi rajouter comment ces formations se déroulent (dans les locaux ou déplacement chez les entreprises, méthodologies), la durée de la formation...

**Comment by EloCvll** [comment]
Obcom, créateur de votre projet Web

Le développement informatique est notre passion, il nous offre la possibilité de créer pour vous et avec vous un véritable **outil de travail sur-mesure** au service des intérêts de votre société et ainsi de **mener à bien vos projets de transformations numériques**.

Implantée à La Rochelle depuis 2010, entreprise à taille humaine, obcom répond à toutes les demandes de développement digitaux web : allant de la conception de logiciels de gestion d'entreprises, à la création de sites internet et d'applications web et bien plus encore.

L'expertise et la complémentarité de notre équipe nous ont permis d'acquérir une technicité et une flexibilité de développement essentielles pour que votre projet voit le jour rapidement. Qu'elle soit simple ou plus complexe, notre mission est d'**apporter une solution digitale** à votre idée de développement informatique.

Obcom s'engage à vos côtés : alors rejoignez-nous !

**Comment by EloCvll** [comment]
On vous accompagne dans votre projet

Depuis la rédaction de votre cahier des charges jusqu'à la livraison et le déploiement de votre outil, nous développons **une relation de travail au quotidien** afin de bien comprendre vos attentes et ainsi appréhender votre projet informatique dans toute sa dimension. Pour ainsi trouver l'équilibre parfait entre **ingéniosité** et **optimisation**.

Nous nous **déplaçons afin d'élaborer avec vous** votre cahier des charges, car même si aujourd'hui tout peut se dématérialiser, nous sommes convaincus qu'un accompagnement physique permet une meilleure approche de votre projet numérique. Une **écoute active** sera de mise pour comprendre votre activité avant de vous aider à clairement formuler vos besoins informatiques.

**Comment by EloCvll** [comment]
Services

Obcom intervient sur vos projets informatiques:

(Rajouter un petit + ou "en savoir plus" sous Logiciel de gestion d'entreprise pour ouvrir une nouvelle page ou sur la même page, au choix)

Ajouter le logo de Somovers

Présentation:

**Outil digital intuitif**, ce logiciel informatique dédié aux entreprises du déménagement est accessible par tous vos collaborateurs et vos clients depuis **une simple connexion internet**. Vous bénéficierez d'une **dématérialisation totale de vos documents**, d'une **sécurisation** et d'une **sauvegarde permanente de vos données**, sans limite de temps.

Il permet en autre, une circulation des dossiers inter-agence **fluide** puisque l'information est stockée sur un **cloud**. Grâce à ce cloud, le dossier de déménagement devient ainsi accessible au déménagé qui possède son espace pour consulter l'évolution de son dossier et y déposer des documents.

**Comment by EloCvll** [comment]
Pour la partie SERVICES, 

E-commerce et Site Web : ajouter une sorte de portfolio ou "ceux qui nous ont fait confiance" avec possibilité d'être dirigé sur leur site.

**Comment by EloCvll** [comment]
Formation

Enregistré en tant que prestataire de formation professionnelle continue, Obcom vous assure une formation sur votre outil informatique fraîchement déployé. Ainsi les différents collaborateurs de l'entreprise seront accompagnés dans l'apprentissage de leur nouveau logiciel web grâce à une **présence physique** ou par une **assistance téléphonique**, selon vos besoins.

**Comment by Zenoo** [comment]
Merged in fe56d690a91c4a3a08507b38a91c25d641d4cfc5
